// Externalized vocab data used by script.js
// Defines a global `VocabData` for backward compatibility with the existing code.
window.VocabData = {
  hsk1: [
    { char: "你好", pinyin: "ni3hao3" },
    { char: "谢谢", pinyin: "xie4xie" },
    { char: "爸爸", pinyin: "ba4ba" },
    { char: "妈妈", pinyin: "ma1ma" },
    { char: "喜欢", pinyin: "xi3huan1" },
    { char: "中国", pinyin: "zhong1guo2" },
    { char: "再见", pinyin: "zai4jian4" },
    { char: "名字", pinyin: "ming2zi4" },
    { char: "什么", pinyin: "shen2me" },
    { char: "高兴", pinyin: "gao1xing4" },
    { char: "是", pinyin: "shi4" },
    { char: "的", pinyin: "de" },
    { char: "和", pinyin: "he2" },
    { char: "一", pinyin: "yi1" },
    { char: "个", pinyin: "ge4" },
    { char: "人", pinyin: "ren2" },
    { char: "大", pinyin: "da4" },
    { char: "小", pinyin: "xiao3" },
    { char: "多", pinyin: "duo1" },
    { char: "少", pinyin: "shao3" },
    { char: "好", pinyin: "hao3" },
    { char: "不好", pinyin: "bu4hao3" },
    { char: "老师", pinyin: "lao3shi1" },
    { char: "学生", pinyin: "xue2sheng1" },
    { char: "朋友", pinyin: "peng2you" },
    { char: "家", pinyin: "jia1" },
    { char: "学校", pinyin: "xue2xiao4" },
    { char: "工作", pinyin: "gong1zuo4" },
    { char: "学习", pinyin: "xue2xi2" },
    { char: "吃饭", pinyin: "chi1fan4" },
    { char: "睡觉", pinyin: "shui4jiao4" },
    { char: "今天", pinyin: "jin1tian1" },
    { char: "明天", pinyin: "ming2tian1" },
    { char: "昨天", pinyin: "zuo2tian1" },
    { char: "早上", pinyin: "zao3shang" },
    { char: "中午", pinyin: "zhong1wu3" },
    { char: "晚上", pinyin: "wan3shang" },
    { char: "现在", pinyin: "xian4zai4" },
    { char: "对", pinyin: "dui4" },
    { char: "错", pinyin: "cuo4" },
  ],
  hsk2: [
    { char: "哥哥", pinyin: "ge1ge" },
    { char: "姐姐", pinyin: "jie3jie" },
    { char: "弟弟", pinyin: "di4di" },
    { char: "妹妹", pinyin: "mei4mei" },
    { char: "快乐", pinyin: "kuai4le" },
    { char: "礼物", pinyin: "li3wu4" },
    { char: "电影", pinyin: "dian4ying3" },
    { char: "音乐", pinyin: "yin1yue4" },
    { char: "考试", pinyin: "kao3shi4" },
    { char: "问题", pinyin: "wen4ti2" },
    { char: "回答", pinyin: "hui2da2" },
    { char: "准备", pinyin: "zhun3bei4" },
    { char: "帮助", pinyin: "bang1zhu4" },
    { char: "觉得", pinyin: "jue2de" },
    { char: "想要", pinyin: "xiang3yao4" },
    { char: "需要", pinyin: "xu1yao4" },
    { char: "运动", pinyin: "yun4dong4" },
    { char: "跑步", pinyin: "pao3bu4" },
    { char: "游泳", pinyin: "you2yong3" },
    { char: "踢足球", pinyin: "ti1zu2qiu2" },
    { char: "旅行", pinyin: "lv3xing2" },
    { char: "飞机", pinyin: "fei1ji1" },
    { char: "机场", pinyin: "ji1chang3" },
    { char: "公共汽车", pinyin: "gong1gong4qi4che1" },
    { char: "地铁", pinyin: "di4tie3" },
    { char: "超市", pinyin: "chao1shi4" },
    { char: "饭馆", pinyin: "fan4guan3" },
    { char: "医生", pinyin: "yi1sheng1" },
    { char: "生病", pinyin: "sheng1bing4" },
    { char: "药", pinyin: "yao4" },
    { char: "苹果", pinyin: "ping2guo3" },
    { char: "牛奶", pinyin: "niu2nai3" },
    { char: "咖啡", pinyin: "ka1fei1" },
    { char: "累", pinyin: "lei4" },
    { char: "忙", pinyin: "mang2" },
  ],
  getList(key) {
    return this[key] || this.hsk1;
  },
};
